"""mise a jour 1

Revision ID: 49959be0fa53
Revises: 
Create Date: 2025-12-01 13:19:18.273056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49959be0fa53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
